name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show workspace files (debug)
        run: |
          pwd
          ls -la
          echo "--- tree ---"
          sudo apt-get update && sudo apt-get install -y tree >/dev/null
          tree -L 2
          echo "--- package.json head ---"
          [ -f package.json ] && head -n 30 package.json || echo "package.json NOT FOUND"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps (root)
        run: npm ci
        working-directory: .

      - name: Run Cypress headless
        run: npx cypress run
        working-directory: .

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
          if-no-files-found: ignore
