name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show workspace files (debug)
        run: |
          pwd
          ls -la
          echo "--- tree ---"
          sudo apt-get update && sudo apt-get install -y tree >/dev/null
          tree -L 2 || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run Cypress headless
        run: npx cypress run

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            booking-cypress-test/cypress/screenshots
            booking-cypress-test/cypress/videos
            booking-cypress-test/cypress/reports
          if-no-files-found: ignore
